# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas/janela_pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdfMerger(object):
    def setupUi(self, pdfMerger):
        pdfMerger.setObjectName("pdfMerger")
        pdfMerger.resize(748, 416)
        self.label_7 = QtWidgets.QLabel(pdfMerger)
        self.label_7.setGeometry(QtCore.QRect(-10, -11, 771, 61))
        self.label_7.setStyleSheet("background: black;")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(pdfMerger)
        self.label_5.setGeometry(QtCore.QRect(4, 10, 741, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(pdfMerger)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("janelas\\../static/apple-touch-icon.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.btnSobe = QtWidgets.QPushButton(pdfMerger)
        self.btnSobe.setGeometry(QtCore.QRect(540, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSobe.setFont(font)
        self.btnSobe.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnSobe.setObjectName("btnSobe")
        self.btnDesce = QtWidgets.QPushButton(pdfMerger)
        self.btnDesce.setGeometry(QtCore.QRect(640, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnDesce.setFont(font)
        self.btnDesce.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnDesce.setObjectName("btnDesce")
        self.btnJuntar = QtWidgets.QPushButton(pdfMerger)
        self.btnJuntar.setGeometry(QtCore.QRect(540, 360, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnJuntar.setFont(font)
        self.btnJuntar.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnJuntar.setObjectName("btnJuntar")
        self.btnApagar = QtWidgets.QPushButton(pdfMerger)
        self.btnApagar.setGeometry(QtCore.QRect(540, 210, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnApagar.setFont(font)
        self.btnApagar.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnApagar.setObjectName("btnApagar")
        self.btnApagarTodos = QtWidgets.QPushButton(pdfMerger)
        self.btnApagarTodos.setGeometry(QtCore.QRect(540, 260, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnApagarTodos.setFont(font)
        self.btnApagarTodos.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnApagarTodos.setObjectName("btnApagarTodos")

        self.retranslateUi(pdfMerger)
        QtCore.QMetaObject.connectSlotsByName(pdfMerger)
        pdfMerger.setTabOrder(self.btnSobe, self.btnDesce)
        pdfMerger.setTabOrder(self.btnDesce, self.btnApagar)
        pdfMerger.setTabOrder(self.btnApagar, self.btnApagarTodos)
        pdfMerger.setTabOrder(self.btnApagarTodos, self.btnJuntar)

    def retranslateUi(self, pdfMerger):
        _translate = QtCore.QCoreApplication.translate
        pdfMerger.setWindowTitle(_translate("pdfMerger", "JUNTAR PDF"))
        self.label_5.setText(_translate("pdfMerger", "JUNTAR PDF"))
        self.btnSobe.setText(_translate("pdfMerger", "SOBE"))
        self.btnDesce.setText(_translate("pdfMerger", "DESCE"))
        self.btnJuntar.setText(_translate("pdfMerger", "JUNTAR PDF"))
        self.btnApagar.setText(_translate("pdfMerger", "APAGAR ARQUIVO"))
        self.btnApagarTodos.setText(_translate("pdfMerger", "APAGAR TODOS \n"
" ARQUIVOS"))
