# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas\janela_arquivos_orcamentos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(722, 479)
        mainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: #F0F0F0\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputPedido = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPedido.setGeometry(QtCore.QRect(110, 369, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.inputPedido.setFont(font)
        self.inputPedido.setStyleSheet("QLineEdit {\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border: 1px solid #CDC99B;\n"
"}")
        self.inputPedido.setAlignment(QtCore.Qt.AlignCenter)
        self.inputPedido.setReadOnly(False)
        self.inputPedido.setClearButtonEnabled(False)
        self.inputPedido.setObjectName("inputPedido")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 380, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 410, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.inputIndice = QtWidgets.QLineEdit(self.centralwidget)
        self.inputIndice.setGeometry(QtCore.QRect(110, 399, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.inputIndice.setFont(font)
        self.inputIndice.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #CDC99B;\n"
"}")
        self.inputIndice.setAlignment(QtCore.Qt.AlignCenter)
        self.inputIndice.setReadOnly(False)
        self.inputIndice.setObjectName("inputIndice")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(330, 70, 381, 341))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setStyleSheet("QTreeWidget {\n"
"\n"
"}")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 440, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.inputArquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.inputArquivo.setGeometry(QtCore.QRect(110, 429, 441, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.inputArquivo.setFont(font)
        self.inputArquivo.setStyleSheet("QLineEdit {\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border: 1px solid #CDC99B;\n"
"    padding-left: 5px;\n"
"}")
        self.inputArquivo.setText("")
        self.inputArquivo.setClearButtonEnabled(False)
        self.inputArquivo.setObjectName("inputArquivo")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 70, 301, 291))
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    border: 0px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tab_1.setStyleSheet("QWidget {\n"
"    background-color: #F0F0F0;\n"
"}")
        self.tab_1.setObjectName("tab_1")
        self.btnApagar = QtWidgets.QPushButton(self.tab_1)
        self.btnApagar.setGeometry(QtCore.QRect(30, 190, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnApagar.setFont(font)
        self.btnApagar.setStyleSheet("QPushButton {\n"
"    background-color: #CDC99B;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    color: red;\n"
"}")
        self.btnApagar.setObjectName("btnApagar")
        self.btnArquivar = QtWidgets.QPushButton(self.tab_1)
        self.btnArquivar.setGeometry(QtCore.QRect(30, 140, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnArquivar.setFont(font)
        self.btnArquivar.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(0,0,0);\n"
"    background-color: #CDC99B;\n"
"    color: white;\n"
"}")
        self.btnArquivar.setObjectName("btnArquivar")
        self.btnSelecionarPedido = QtWidgets.QPushButton(self.tab_1)
        self.btnSelecionarPedido.setEnabled(True)
        self.btnSelecionarPedido.setGeometry(QtCore.QRect(30, 20, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelecionarPedido.setFont(font)
        self.btnSelecionarPedido.setStyleSheet("QPushButton {\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border: 1px solid rgb(0,0,0);\n"
"    background-color: #CDC99B;\n"
"    color: white;\n"
"}")
        self.btnSelecionarPedido.setObjectName("btnSelecionarPedido")
        self.btnAbrirArquivo = QtWidgets.QPushButton(self.tab_1)
        self.btnAbrirArquivo.setGeometry(QtCore.QRect(30, 70, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAbrirArquivo.setFont(font)
        self.btnAbrirArquivo.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(0,0,0);\n"
"    background-color: #CDC99B;\n"
"    color: white;\n"
"}")
        self.btnAbrirArquivo.setObjectName("btnAbrirArquivo")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QWidget {\n"
"    background-color: #F0F0F0;\n"
"}")
        self.tab_2.setObjectName("tab_2")
        self.btnEstornar = QtWidgets.QPushButton(self.tab_2)
        self.btnEstornar.setGeometry(QtCore.QRect(30, 190, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnEstornar.setFont(font)
        self.btnEstornar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}")
        self.btnEstornar.setObjectName("btnEstornar")
        self.btnExcluirPedido = QtWidgets.QPushButton(self.tab_2)
        self.btnExcluirPedido.setGeometry(QtCore.QRect(30, 70, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnExcluirPedido.setFont(font)
        self.btnExcluirPedido.setStyleSheet("QPushButton {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    color: red;\n"
"}")
        self.btnExcluirPedido.setObjectName("btnExcluirPedido")
        self.btnLiquidar = QtWidgets.QPushButton(self.tab_2)
        self.btnLiquidar.setGeometry(QtCore.QRect(30, 130, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnLiquidar.setFont(font)
        self.btnLiquidar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}")
        self.btnLiquidar.setObjectName("btnLiquidar")
        self.btnIncluirPedido = QtWidgets.QPushButton(self.tab_2)
        self.btnIncluirPedido.setGeometry(QtCore.QRect(30, 20, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnIncluirPedido.setFont(font)
        self.btnIncluirPedido.setStyleSheet("QPushButton {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}")
        self.btnIncluirPedido.setObjectName("btnIncluirPedido")
        self.tabWidget.addTab(self.tab_2, "")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(-10, -10, 1071, 61))
        self.label_10.setStyleSheet("background: black;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(0, 10, 721, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("janelas\\../static/apple-touch-icon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.btnAtualizarNumPedido = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtualizarNumPedido.setGeometry(QtCore.QRect(560, 430, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btnAtualizarNumPedido.setFont(font)
        self.btnAtualizarNumPedido.setStyleSheet("QPushButton {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"}")
        self.btnAtualizarNumPedido.setObjectName("btnAtualizarNumPedido")
        self.treeWidget.raise_()
        self.inputPedido.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.inputIndice.raise_()
        self.label_4.raise_()
        self.inputArquivo.raise_()
        self.tabWidget.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.btnAtualizarNumPedido.raise_()
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.inputPedido, self.btnSelecionarPedido)
        mainWindow.setTabOrder(self.btnSelecionarPedido, self.btnAbrirArquivo)
        mainWindow.setTabOrder(self.btnAbrirArquivo, self.btnArquivar)
        mainWindow.setTabOrder(self.btnArquivar, self.btnApagar)
        mainWindow.setTabOrder(self.btnApagar, self.tabWidget)
        mainWindow.setTabOrder(self.tabWidget, self.treeWidget)
        mainWindow.setTabOrder(self.treeWidget, self.inputIndice)
        mainWindow.setTabOrder(self.inputIndice, self.inputArquivo)
        mainWindow.setTabOrder(self.inputArquivo, self.btnEstornar)
        mainWindow.setTabOrder(self.btnEstornar, self.btnExcluirPedido)
        mainWindow.setTabOrder(self.btnExcluirPedido, self.btnLiquidar)
        mainWindow.setTabOrder(self.btnLiquidar, self.btnIncluirPedido)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "SII - Pedidos"))
        self.label.setText(_translate("mainWindow", "Orçamento:"))
        self.label_2.setText(_translate("mainWindow", "Indice:"))
        self.label_4.setText(_translate("mainWindow", "Arquivo:"))
        self.btnApagar.setText(_translate("mainWindow", "Apagar Arquivo"))
        self.btnArquivar.setText(_translate("mainWindow", "Arquivar"))
        self.btnSelecionarPedido.setText(_translate("mainWindow", "Buscar Orçamento"))
        self.btnAbrirArquivo.setText(_translate("mainWindow", "Incluir Arquivo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("mainWindow", "ARQUIVOS"))
        self.btnEstornar.setText(_translate("mainWindow", "Estornar"))
        self.btnExcluirPedido.setText(_translate("mainWindow", "Excluir"))
        self.btnLiquidar.setText(_translate("mainWindow", "Liquidar"))
        self.btnIncluirPedido.setText(_translate("mainWindow", "Incluir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "ORÇAMENTOS"))
        self.label_11.setText(_translate("mainWindow", "SISTEMA INTERNO INAFLEX - SII - MODULO ARQUIVOS"))
        self.btnAtualizarNumPedido.setText(_translate("mainWindow", "Atualizar Pedido"))
