# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas\janela_estudo_demanda.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_estudo_demanda(object):
    def setupUi(self, estudo_demanda):
        estudo_demanda.setObjectName("estudo_demanda")
        estudo_demanda.resize(400, 210)
        self.label_2 = QtWidgets.QLabel(estudo_demanda)
        self.label_2.setGeometry(QtCore.QRect(-4, -11, 411, 61))
        self.label_2.setStyleSheet("background: black;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(estudo_demanda)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("janelas\\../static/apple-touch-icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(estudo_demanda)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btnSelect = QtWidgets.QPushButton(estudo_demanda)
        self.btnSelect.setGeometry(QtCore.QRect(20, 70, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelect.setFont(font)
        self.btnSelect.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnSelect.setObjectName("btnSelect")
        self.data_inicial = QtWidgets.QDateEdit(estudo_demanda)
        self.data_inicial.setGeometry(QtCore.QRect(140, 160, 241, 31))
        self.data_inicial.setStyleSheet("QDateEdit\n"
"{\n"
"border : 2px solid black;\n"
"background-color : white;\n"
"padding : 5px;\n"
"padding-left: 80px;\n"
"font-size: 15px;\n"
"}\n"
"")
        self.data_inicial.setObjectName("data_inicial")
        self.label = QtWidgets.QLabel(estudo_demanda)
        self.label.setGeometry(QtCore.QRect(30, 167, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(estudo_demanda)
        QtCore.QMetaObject.connectSlotsByName(estudo_demanda)

    def retranslateUi(self, estudo_demanda):
        _translate = QtCore.QCoreApplication.translate
        estudo_demanda.setWindowTitle(_translate("estudo_demanda", "SII - Uteis"))
        self.label_4.setText(_translate("estudo_demanda", "ESTUDO DEMANDA"))
        self.btnSelect.setText(_translate("estudo_demanda", "SELECIONAR ARQUIVO"))
        self.label.setText(_translate("estudo_demanda", "DATA INICIAL:"))
