# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas\janela_arquivos_arquivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaIncluirArquivos(object):
    def setupUi(self, telaIncluirArquivos):
        telaIncluirArquivos.setObjectName("telaIncluirArquivos")
        telaIncluirArquivos.resize(749, 281)
        self.labelErro = QtWidgets.QLabel(telaIncluirArquivos)
        self.labelErro.setGeometry(QtCore.QRect(0, 0, 751, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.labelErro.setFont(font)
        self.labelErro.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.labelErro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelErro.setObjectName("labelErro")
        self.btnIncluirPedidoTela = QtWidgets.QPushButton(telaIncluirArquivos)
        self.btnIncluirPedidoTela.setGeometry(QtCore.QRect(40, 170, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIncluirPedidoTela.setFont(font)
        self.btnIncluirPedidoTela.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgb(0,0,0);\n"
"    background-color: #CDC99B;\n"
"    color: white;\n"
"}")
        self.btnIncluirPedidoTela.setObjectName("btnIncluirPedidoTela")
        self.inputIncluirIndice = QtWidgets.QLineEdit(telaIncluirArquivos)
        self.inputIncluirIndice.setGeometry(QtCore.QRect(40, 103, 113, 31))
        self.inputIncluirIndice.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    border: 1px solid #CDC99B;\n"
"}")
        self.inputIncluirIndice.setAlignment(QtCore.Qt.AlignCenter)
        self.inputIncluirIndice.setObjectName("inputIncluirIndice")
        self.checkIncluirAtual = QtWidgets.QCheckBox(telaIncluirArquivos)
        self.checkIncluirAtual.setGeometry(QtCore.QRect(140, 140, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkIncluirAtual.setFont(font)
        self.checkIncluirAtual.setStyleSheet("QLineEdit {\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border: 1px solid #CDC99B;\n"
"}")
        self.checkIncluirAtual.setObjectName("checkIncluirAtual")
        self.label_2 = QtWidgets.QLabel(telaIncluirArquivos)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(telaIncluirArquivos)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 451, 191))
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: rgb(188, 188, 188);\n"
"    border-radius: 15px;\n"
"}")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(telaIncluirArquivos)
        self.label_4.setGeometry(QtCore.QRect(-4, -8, 761, 61))
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: #CDC99B;\n"
"}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(telaIncluirArquivos)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(290, 120, 211, 131))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"    border: 0px;\n"
"}")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(telaIncluirArquivos)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(510, 120, 211, 131))
        self.plainTextEdit_2.setStyleSheet("QPlainTextEdit {\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_5 = QtWidgets.QLabel(telaIncluirArquivos)
        self.label_5.setGeometry(QtCore.QRect(280, 70, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    background: black;\n"
"    color: white;\n"
"    border: 1px solid #CDC99B;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 15px;\n"
"}\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.labelPedido = QtWidgets.QLabel(telaIncluirArquivos)
        self.labelPedido.setGeometry(QtCore.QRect(40, 70, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelPedido.setFont(font)
        self.labelPedido.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPedido.setObjectName("labelPedido")
        self.btnCancela = QtWidgets.QPushButton(telaIncluirArquivos)
        self.btnCancela.setGeometry(QtCore.QRect(40, 220, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancela.setFont(font)
        self.btnCancela.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgb(0,0,0);\n"
"    background-color: #CDC99B;\n"
"    color: white;\n"
"}")
        self.btnCancela.setObjectName("btnCancela")
        self.label_4.raise_()
        self.labelErro.raise_()
        self.btnIncluirPedidoTela.raise_()
        self.inputIncluirIndice.raise_()
        self.checkIncluirAtual.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.label_5.raise_()
        self.labelPedido.raise_()
        self.btnCancela.raise_()

        self.retranslateUi(telaIncluirArquivos)
        QtCore.QMetaObject.connectSlotsByName(telaIncluirArquivos)
        telaIncluirArquivos.setTabOrder(self.inputIncluirIndice, self.checkIncluirAtual)
        telaIncluirArquivos.setTabOrder(self.checkIncluirAtual, self.btnIncluirPedidoTela)
        telaIncluirArquivos.setTabOrder(self.btnIncluirPedidoTela, self.btnCancela)
        telaIncluirArquivos.setTabOrder(self.btnCancela, self.plainTextEdit)
        telaIncluirArquivos.setTabOrder(self.plainTextEdit, self.plainTextEdit_2)

    def retranslateUi(self, telaIncluirArquivos):
        _translate = QtCore.QCoreApplication.translate
        telaIncluirArquivos.setWindowTitle(_translate("telaIncluirArquivos", "INCLUIR PEDIDO"))
        self.labelErro.setText(_translate("telaIncluirArquivos", "Incluir Arquivo"))
        self.btnIncluirPedidoTela.setText(_translate("telaIncluirArquivos", "Incluir"))
        self.checkIncluirAtual.setText(_translate("telaIncluirArquivos", "Arquivo"))
        self.label_2.setText(_translate("telaIncluirArquivos", "Indice"))
        self.plainTextEdit.setPlainText(_translate("telaIncluirArquivos", "01 - ORÇAMENTO DOUBLE CHECK\n"
"02 - PEDIDO DO CLIENTE\n"
"03 - COTAÇÃO DO FORNECEDOR\n"
"04 - ANALISE DE CONTRATO\n"
"05 - CROQUIS, DESENHOS, PLAQUETAS\n"
"06 - DESVIOS\n"
"07 - SOLICITAÇÃO DO CLIENTE\n"
"08 - ORCAMENTO ENVIADO"))
        self.plainTextEdit_2.setPlainText(_translate("telaIncluirArquivos", "09 - PIT\n"
"10 - INFO RELEV. PRODUÇÃO\n"
"11 - INFO RELEV. ENTREGA\n"
"12 - INFO RELEV. FATURAMENTO\n"
"13 - INFO RELEV. INSPEÇÃO\n"
"14 - INFO RELEV. DIRETORIA\n"
"15 - OUTROS ARQUIVOS"))
        self.label_5.setText(_translate("telaIncluirArquivos", "LEGENDA"))
        self.labelPedido.setText(_translate("telaIncluirArquivos", "Selecionar Pedido"))
        self.btnCancela.setText(_translate("telaIncluirArquivos", "Cancelar"))
