# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas\janela_estudo_pedidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_estudo_pedido(object):
    def setupUi(self, estudo_pedido):
        estudo_pedido.setObjectName("estudo_pedido")
        estudo_pedido.resize(400, 210)
        self.label_2 = QtWidgets.QLabel(estudo_pedido)
        self.label_2.setGeometry(QtCore.QRect(-4, -11, 411, 61))
        self.label_2.setStyleSheet("background: black;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(estudo_pedido)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("janelas\\../static/apple-touch-icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(estudo_pedido)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btnCalcular = QtWidgets.QPushButton(estudo_pedido)
        self.btnCalcular.setGeometry(QtCore.QRect(260, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnCalcular.setFont(font)
        self.btnCalcular.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnCalcular.setObjectName("btnCalcular")
        self.inputPedido = QtWidgets.QLineEdit(estudo_pedido)
        self.inputPedido.setGeometry(QtCore.QRect(90, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.inputPedido.setFont(font)
        self.inputPedido.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid #CDC99B;")
        self.inputPedido.setAlignment(QtCore.Qt.AlignCenter)
        self.inputPedido.setReadOnly(False)
        self.inputPedido.setClearButtonEnabled(False)
        self.inputPedido.setObjectName("inputPedido")
        self.label_pedido = QtWidgets.QLabel(estudo_pedido)
        self.label_pedido.setGeometry(QtCore.QRect(32, 98, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_pedido.setFont(font)
        self.label_pedido.setStyleSheet("color: black;\n"
"font: bold")
        self.label_pedido.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pedido.setObjectName("label_pedido")
        self.label_resultado = QtWidgets.QLabel(estudo_pedido)
        self.label_resultado.setGeometry(QtCore.QRect(32, 150, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_resultado.setFont(font)
        self.label_resultado.setStyleSheet("color: black;\n"
"font: bold")
        self.label_resultado.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_resultado.setObjectName("label_resultado")
        self.label_valor = QtWidgets.QLabel(estudo_pedido)
        self.label_valor.setGeometry(QtCore.QRect(90, 150, 281, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_valor.setFont(font)
        self.label_valor.setStyleSheet("color: black;\n"
"font: bold")
        self.label_valor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_valor.setObjectName("label_valor")

        self.retranslateUi(estudo_pedido)
        QtCore.QMetaObject.connectSlotsByName(estudo_pedido)

    def retranslateUi(self, estudo_pedido):
        _translate = QtCore.QCoreApplication.translate
        estudo_pedido.setWindowTitle(_translate("estudo_pedido", "SII - Uteis"))
        self.label_4.setText(_translate("estudo_pedido", "ANALISE DE CUSTO DO PEDIDO"))
        self.btnCalcular.setText(_translate("estudo_pedido", "CALCULAR"))
        self.label_pedido.setText(_translate("estudo_pedido", "ITEM"))
        self.label_resultado.setText(_translate("estudo_pedido", "CUSTO:"))
        self.label_valor.setText(_translate("estudo_pedido", "ITEM"))
