# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janelas\janela_uteis.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uteis(object):
    def setupUi(self, uteis):
        uteis.setObjectName("uteis")
        uteis.resize(406, 351)
        self.btnPdf = QtWidgets.QPushButton(uteis)
        self.btnPdf.setGeometry(QtCore.QRect(20, 70, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPdf.setFont(font)
        self.btnPdf.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnPdf.setObjectName("btnPdf")
        self.label_2 = QtWidgets.QLabel(uteis)
        self.label_2.setGeometry(QtCore.QRect(-4, -11, 411, 61))
        self.label_2.setStyleSheet("background: black;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(uteis)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("janelas\\../static/apple-touch-icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(uteis)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btnDemanda = QtWidgets.QPushButton(uteis)
        self.btnDemanda.setGeometry(QtCore.QRect(153, 70, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnDemanda.setFont(font)
        self.btnDemanda.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnDemanda.setObjectName("btnDemanda")
        self.btnEstudoDemanda = QtWidgets.QPushButton(uteis)
        self.btnEstudoDemanda.setGeometry(QtCore.QRect(290, 170, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEstudoDemanda.setFont(font)
        self.btnEstudoDemanda.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnEstudoDemanda.setObjectName("btnEstudoDemanda")
        self.btnSelect = QtWidgets.QPushButton(uteis)
        self.btnSelect.setGeometry(QtCore.QRect(290, 70, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelect.setFont(font)
        self.btnSelect.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnSelect.setObjectName("btnSelect")
        self.btnAnaliseOps = QtWidgets.QPushButton(uteis)
        self.btnAnaliseOps.setGeometry(QtCore.QRect(20, 170, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAnaliseOps.setFont(font)
        self.btnAnaliseOps.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnAnaliseOps.setObjectName("btnAnaliseOps")
        self.btnInspecao = QtWidgets.QPushButton(uteis)
        self.btnInspecao.setGeometry(QtCore.QRect(153, 170, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnInspecao.setFont(font)
        self.btnInspecao.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnInspecao.setObjectName("btnInspecao")
        self.btnEstudoPedido = QtWidgets.QPushButton(uteis)
        self.btnEstudoPedido.setGeometry(QtCore.QRect(290, 260, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEstudoPedido.setFont(font)
        self.btnEstudoPedido.setStyleSheet("border-radius: 10px; border: 1px solid rgb(0,0,0);  background-color: #CDC99B;    color: white;")
        self.btnEstudoPedido.setObjectName("btnEstudoPedido")

        self.retranslateUi(uteis)
        QtCore.QMetaObject.connectSlotsByName(uteis)

    def retranslateUi(self, uteis):
        _translate = QtCore.QCoreApplication.translate
        uteis.setWindowTitle(_translate("uteis", "SII - Uteis"))
        self.btnPdf.setText(_translate("uteis", "PDF"))
        self.label_4.setText(_translate("uteis", "UTEIS"))
        self.btnDemanda.setText(_translate("uteis", "DEMANDA\n"
" POR ITEM"))
        self.btnEstudoDemanda.setText(_translate("uteis", "ESTUDO \n"
" DEMANDA"))
        self.btnSelect.setText(_translate("uteis", "SELECT"))
        self.btnAnaliseOps.setText(_translate("uteis", "ANALISE \n"
" OPS/OCS"))
        self.btnInspecao.setText(_translate("uteis", "RELATÓRIO\n"
" INSPEÇÃO"))
        self.btnEstudoPedido.setText(_translate("uteis", "ESTUDO \n"
" PEDIDO"))
